import sys
import hou
import soho
from soho import SohoParam


def render():
    """Main execution loop called by Houdini's SOHO framework."""

    # 1. Initialize SOHO with the current time/frame
    now = soho.getFloat("now")[0]

    # 2. Configure output control options
    # Telling SOHO to evaluate the scene based on this ROP node
    soho.initialize(now, "")
    print("SOHO initialized")
    '''
    # 3. Retrieve target file path from the ROP parameters
    # Assumes your ROP has a standard 'output' or 'soho_outputfile' parameter
    output_file = soho.getString("soho_outputfile")[0]

    # 4. Open your output file stream (or stream to stdout)
    with open(output_file, "w") as f:
        f.write("# Custom Export Generated by SOHO\n")

        # 5. Loop through geometry/objects in the scene
        # 'objlist:allobjects' fetches objects based on ROP visibility settings
        for obj in soho.objectList("objlist:allobjects", now):
            # Get internal Houdini node reference from SOHO object
            path = obj.getName()
            f.write(f"object {path}\n")

            # Fetch specific parameters from the object
            # SOHO evaluates motion blur, transformations, and custom spare parms
            matrix = obj.getDefaultMatrix(now)
            f.write(f"  transform {list(matrix)}\n")
    '''
    # 6. Finalize the SOHO process cleanly
    soho.finalize()
