
import hou

def callback(input):
    node = input.get("node")
    job_name = node.evalParm("job_name")
    print(f"job_name: {job_name}")
    job_start_paused = node.evalParm("job_start_paused")
    print(f"job_start_paused: {job_start_paused}")
    job_priority = node.evalParm("job_priority")
    print(f"job_priority: {job_priority}")
    input_node = node.evalParm("input_node")
    print(f"input_node: {input_node}")
    layer_type = node.evalParm("layer_type")
    print(f"layer_type: {layer_type}")
    trange = node.evalParm("trange")
    print(f"trange: {trange}")
    f = node.evalParmTuple("f")
    print(f)
    # print(f"f: {f}")
    layer_frames_per_task = node.evalParm("layer_frames_per_task")
    print(f"layer_frames_per_task: {layer_frames_per_task}")
    layer_singletask = node.evalParm("layer_singletask")
    print(f"layer_singletask: {layer_singletask}")
    layer_memory_min = node.evalParm("layer_memory_min")
    print(f"layer_memory_min: {layer_memory_min}")
    layer_memory_auto = node.evalParm("layer_memory_auto")
    print(f"layer_memory_auto: {layer_memory_auto}")
    layer_threads = node.evalParm("layer_threads")
    print(f"layer_threads: {layer_threads}")
    layer_threads_min_max = node.evalParmTuple("layer_threads_min_max")
    print(layer_threads_min_max)
    # print(f"layer_threads_min_max: {layer_threads_min_max}")
    layer_dependency_type = node.evalParm("layer_dependency_type")
    print(f"layer_dependency_type: {layer_dependency_type}")
    